# -*- coding: utf-8 -*-
"""Asign1_NBA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HIc6bYIhG8GNdjokffcPdq1ywvhfwbjt
"""

from google.colab import files
files.upload()

import pandas as pd
#dataframe
df = pd.read_csv("nba_2020_advancedd.csv")
print(df.head())

#Tm Team Name
#G Games Played
#MP Minutes Played
#PER Player Efficiency Rating
#TS% True Shooting Percentage
#3PAr 3-Point Attempt Rate
#FTr Free Throw Rate

num_df = df[["Age", "G","MP", "PER","TS%", "3PAr", "FTr"]]
print(num_df)

num_df.describe()

num_df.mean()

num_df.median()

num_df.mode()

#filtering AGE values between Q1-1.5IQR AND Q3+1.5IQR
f1_df = num_df['Age']>= 35.5
f2_df = num_df[f1_df]

f3_df = num_df['Age']<= 15.5
f4_df = num_df[f3_df]
print(f2_df)
print(f4_df)

#filtering True Shooting % values between Q1-1.5IQR AND Q3+1.5IQR
f1_df = num_df['TS%']>= .719
f2_df = num_df[f1_df]

f3_df = num_df['TS%']<= .375
f4_df = num_df[f3_df]
print(f2_df)
print(f4_df)

num_df.plot.scatter(
    x = 'PER',
    y = 'MP'
);

num_df.boxplot(column=['3PAr', 'FTr']);